name: React Shared Test

on:
  pull_request:
    branches:
      - main
    paths:
      - "packages/react-shared/src/**"
  push:
    branches:
      - main
    paths:
      - "packages/react-shared/src/**"

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci || npm install

      - name: Run tests
        run: npm run test
