name: React Shared Test

on:
  pull_request:
    branches:
      - main
    paths:
      - "packages/react-shared/src/**"
  push:
    branches:
      - main
    paths:
      - "packages/react-shared/src/**"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: pnpm install

      - name: Run tests
        run: pnpm run test
