name: React Shared Test

on:
  pull_request:
    branches:
      - main
    paths:
      - "packages/react-shared/src/**"
  push:
    branches:
      - main
    paths:
      - "packages/react-shared/src/**"

jobs:
  chromatic-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.16.0"

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        id: pnpm-install
        with:
          version: 8
          run_install: false

      - name: Run tests
        run: pnpm run test
