name: React Shared Test and Auto Merge

on:
  pull_request:
    branches:
      - main
    paths:
      - "packages/typescript-utils/src/**"
  push:
    branches:
      - main
    paths:
      - "packages/typescript-utils/src/**"

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    # To use Remote Caching, uncomment the next lines and follow the steps below.
    # env:
    #  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
    #  TURBO_TEAM: ${{ vars.TURBO_TEAM }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      # - name: Build
      #   run: pnpm build

      - name: Test
        run: pnpm test --filter=@repo/typescript-utils
